source $ZDOTDIR/config/setting.zsh
source $ZDOTDIR/config/env.zsh
source $ZDOTDIR/theme/ys.zsh-theme
source $ZDOTDIR/config/function.zsh
source $ZDOTDIR/config/history.zsh
source $ZDOTDIR/config/fzf.zsh
source $ZDOTDIR/config/plugin.zsh
source $ZDOTDIR/config/alias.zsh
source $ZDOTDIR/config/correction.zsh
