source $ZDOTDIR/config/env_config.zsh
source $ZDOTDIR/config/env_program.zsh
source $ZDOTDIR/config/env_git.zsh
source $ZDOTDIR/config/setting.zsh
source $ZDOTDIR/theme/ys.zsh-theme
source $ZDOTDIR/config/plugin.zsh
source $ZDOTDIR/config/alias.zsh
source $ZDOTDIR/config/function.zsh
source $ZDOTDIR/config/history.zsh
